name: Deploy Rules

on:
  push:
    branches:
      - main
    paths:
      - 'firestore.rules'
      - 'storage.rules'
      - 'firebase.json'

jobs:
  deploy_rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v6.0.9
        with:
          run_install: false

      - uses: actions/setup-node@v7
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - name: Deploy Rules to Staging
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore.rules,storage
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ vars.STG_FIREBASE_PROJECT_ID }}
